// Generated by sfdx-devops-kit — replace with the journeys this project cares
// about. It is written to be honest about its prerequisite: without a target org
// URL there is nothing to test, so the spec skips rather than passing vacuously.
import { expect, test } from "@playwright/test";

const baseURL = process.env.E2E_BASE_URL;

test.describe("Salesforce org smoke", () => {
  test.skip(!baseURL, "E2E_BASE_URL is not set — no org to test against.");

  test("the org serves an authenticated Lightning page", async ({ page }) => {
    // A frontdoor/session URL is the usual way CI arrives authenticated; when the
    // session is missing, Salesforce redirects to login, which this asserts against.
    await page.goto("/lightning/page/home", { waitUntil: "domcontentloaded" });

    const onLoginPage = /\/login|\/secur\/login/.test(page.url());
    expect(
      onLoginPage,
      "Landed on the login page: the E2E session is not authenticated. " +
        "Pass a frontdoor URL or storage state to Playwright.",
    ).toBe(false);

    await expect(page.locator("body")).toBeVisible();
  });
});
